[main]
font=FiraCode Nerd Font:size=24, DejaVu Sans:size=24, Noto Naskh Arabic:size=24
dpi-aware=yes
pad=16x16 center

[scrollback]
lines=10000
multiplier=3

[colors-dark]
alpha=0.7
foreground=e0e0e0
background=000000
selection-foreground=000000
selection-background=7acaca

regular0=000000
regular1=cc5555
regular2=55cc55
regular3=cdcd55
regular4=5555cc
regular5=cc55cc
regular6=7acaca
regular7=cccccc

bright0=555555
bright1=ff5555
bright2=55ff55
bright3=ffff55
bright4=5555ff
bright5=ff55ff
bright6=55ffff
bright7=ffffff

[mouse]
hide-when-typing=yes

[url]
launch=xdg-open ${url}
osc8-underline=always
[url-bindings]
# cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

[tweak]
grapheme-shaping=yes

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste
show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+y